### ISSUE TITLE
elitebook 845 g9 rembrandt security

### ISSUE THREAD

**Issue by pgera** [fwupd/firmware-hp#3]
If you have any contacts at HP, could you please raise this:

`HSI-1
✔ Fused platform:                Locked
✔ Supported CPU:                 Valid
✔ TPM empty PCRs:                Valid
✔ TPM v2.0:                      Found
✔ UEFI platform key:             Valid
✔ UEFI secure boot:              Enabled

HSI-2
✔ IOMMU:                         Enabled
✔ Platform debugging:            Locked
✔ TPM PCR0 reconstruction:       Valid
✘ SPI write protection:          Disabled

HSI-3
✔ Pre-boot DMA protection:       Enabled
✔ Suspend-to-idle:               Enabled
✔ Suspend-to-ram:                Disabled
✘ SPI replay protection:         Not supported

HSI-4
✔ Encrypted RAM:                 Encrypted
✔ Processor rollback protection: Enabled

Runtime Suffix -!
✔ Linux kernel:                  Untainted
✔ Linux kernel lockdown:         Enabled
✔ Linux swap:                    Encrypted
✔ fwupd plugins:                 Untainted

Host Security Events
  2022-12-30 03:41:20:  ✔ Encrypted RAM changed: Not supported → Encrypted

`

**Comment by superm1** [comment]
What's the issue?

**Comment by pgera** [comment]
SPI write protection and SPI replay protection.

**Comment by superm1** [comment]
I don't believe we have any fwupd bug here; this is controlled by the BIOS for the manufacturer and their threat model.  You'll need to contact them to discuss it.
